name: Deploy to EC2
on:
  push: 
    branches:
      - main
jobs: 
  deploy: 
    runs-on: ubuntu-latest
steps: 
    - name: checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build and push Docker image
      run:
        docker build -t dummy-server
        docker tag dummy-server:latest 
